---
kubernetes_role: "control_plane"

kubernetes_allow_pods_on_control_plane: true

kubernetes_pod_network:
  # Flannel CNI.
  cni: 'flannel'
  cidr: '10.244.0.0/16'
  # Calico CNI.
  # cni: 'calico'
  # cidr: '192.168.0.0/16'
