---
- name: Create Kubernetes test infra with Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Apply Terraform
      ansible.builtin.shell: cd ${TF_PROJECT_PATH} && terraform apply -auto-approve
      register: result
      changed_when: "'Apply complete!' in result.stdout"
