---
- name: Destroy Kubernetes infra with Terraform
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Terraform destroy
      ansible.builtin.shell: cd ${TF_PROJECT_PATH} && terraform destroy -auto-approve
      ignore_errors: true
