---
dependency:
  name: galaxy

driver:
  name: default   # Terraform/libvirt provides infra; Molecule only tests

provisioner:
  name: ansible
  playbooks:
    #create: create.yml
    converge: ../../../../playbooks/site.yml
    #verify: verify.yml
    #destroy: destroy.yml
  inventory:
    hostsfile: ${TF_PROJECT_PATH}/terraform.yml
    links:
      group_vars: ../../../../group_vars
  env:
    ANSIBLE_CONFIG: ${ANSIBLE_CONFIG}
    ANSIBLE_HOST_KEY_CHECKING: "False"
    TF_PROJECT_PATH: ${TF_PROJECT_PATH}

verifier:
  name: ansible
  