- hosts: all
  become: yes
  roles:
    - role: pre_kubernetes
    - role: geerlingguy.containerd
    - role: geerlingguy.kubernetes

- hosts: masters
  become: yes
  roles:
    - role: verify
  tags:
    - verify
