---
- name: Initialize Kubernetes control plane
  become: yes
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=all
  args:
    creates: /etc/kubernetes/admin.conf

- name: Configure kubectl for root
  become: yes
  shell: |
    mkdir -p /root/.kube
    cp -i /etc/kubernetes/admin.conf /root/.kube/config
    chown root:root /root/.kube/config

- name: Install CNI plugin (Flannel)
  become: yes
  shell: |
    kubectl --kubeconfig=/etc/kubernetes/admin.conf \
      apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

- name: Get join command
  become: yes
  shell: kubeadm token create --print-join-command
  register: join_cmd

- name: Save join command for workers
  delegate_to: localhost
  copy:
    dest: join-command.sh
    content: "{{ join_cmd.stdout }}"
