apiVersion: v1
kind: ConfigMap
metadata:
  name: sga-web-config
data:
  sga.conf: |
    <VirtualHost *:80>
      ProxyPreserveHost On
      ProxyPass /sga http://sga-app-service:8080/
      ProxyPassReverse /sga http://sga-app-service:8080/
    </VirtualHost>
